sudo: required
services:
  - docker

before_install:
  - docker build -t phunhakent/dev-flow -f Dockerfile.dev .

script:
  - docker run phunhakent/dev-flow npm run test -- --coverage

deploy:
  provider: heroku
  api_key:
    master:
      secure: $HEROKU_DEPLOYMENT_KEY
  app: 
    master: phunhakent--dev-flow